awsRegion: us-east-1

rbac:
  create: true
  serviceAccountAnnotations:
    eks.amazonaws.com/role-arn: "${module.eks.cluster_iam_role_arn}"

autoDiscovery:
  clusterName: "eks-irsa-${lower(terraform.workspace)}"
  enabled: true
